fromaddr: 'example_email@gmail.com'
username: 'example_email@gmail.com'
password: 'example_password'
phone_number_demo: '111-555-5555'
toaddrs_demo: '1115555555@vtext.com'
postgres_username: 'postgres_username'
postgres_password: 'postgres_password'
postgres_db: 'postgres_db_name'
data_dir: 'data_directory'
start_message: 'Welcome to Jobs2Phones. This is the text message sent to new users.'
chosen_message: 'This is the message for after posting categories are chosen from the list.'
stop_message: 'We are sorry to see you go. This is the message for after someone texts "STOP"'